openapi: 3.1.0
info:
  title: Coorp Capsule API
  description: MVP tecnico para gestionar productos, stock y movimientos de inventario.
  version: 1.0.0
paths:
  /:
    get:
      summary: Root
      operationId: root__get
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema: {}
  /health:
    get:
      summary: Health
      operationId: health_health_get
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema: {}
  /products:
    get:
      summary: Listar Productos
      operationId: listar_productos_products_get
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                items:
                  $ref: '#/components/schemas/ProductResponse'
                type: array
                title: Response Listar Productos Products Get
    post:
      summary: Crear Producto
      operationId: crear_producto_products_post
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ProductCreate'
        required: true
      responses:
        '201':
          description: Successful Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProductResponse'
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
  /products/{product_id}:
    get:
      summary: Obtener Producto
      operationId: obtener_producto_products__product_id__get
      parameters:
      - name: product_id
        in: path
        required: true
        schema:
          type: integer
          title: Product Id
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProductResponse'
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
    put:
      summary: Actualizar Producto
      operationId: actualizar_producto_products__product_id__put
      parameters:
      - name: product_id
        in: path
        required: true
        schema:
          type: integer
          title: Product Id
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ProductUpdate'
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProductResponse'
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
  /products/{product_id}/status:
    patch:
      summary: Cambiar Estado Producto
      operationId: cambiar_estado_producto_products__product_id__status_patch
      parameters:
      - name: product_id
        in: path
        required: true
        schema:
          type: integer
          title: Product Id
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ProductStatusUpdate'
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProductResponse'
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
  /movements:
    post:
      summary: Registrar Movimiento
      operationId: registrar_movimiento_movements_post
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/MovementCreate'
        required: true
      responses:
        '201':
          description: Successful Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MovementResponse'
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
  /products/{product_id}/movements:
    get:
      summary: Listar Movimientos Producto
      operationId: listar_movimientos_producto_products__product_id__movements_get
      parameters:
      - name: product_id
        in: path
        required: true
        schema:
          type: integer
          title: Product Id
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/MovementResponse'
                title: Response Listar Movimientos Producto Products  Product Id  Movements
                  Get
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
components:
  schemas:
    HTTPValidationError:
      properties:
        detail:
          items:
            $ref: '#/components/schemas/ValidationError'
          type: array
          title: Detail
      type: object
      title: HTTPValidationError
    MovementCreate:
      properties:
        producto_id:
          type: integer
          exclusiveMinimum: 0.0
          title: Producto Id
        tipo:
          type: string
          enum:
          - entrada
          - salida
          title: Tipo
        cantidad:
          type: integer
          exclusiveMinimum: 0.0
          title: Cantidad
          description: Cantidad mayor que 0
        descripcion:
          type: string
          maxLength: 200
          minLength: 1
          title: Descripcion
      type: object
      required:
      - producto_id
      - tipo
      - cantidad
      - descripcion
      title: MovementCreate
    MovementResponse:
      properties:
        id:
          type: integer
          title: Id
        producto_id:
          type: integer
          title: Producto Id
        tipo:
          type: string
          enum:
          - entrada
          - salida
          title: Tipo
        cantidad:
          type: integer
          title: Cantidad
        descripcion:
          type: string
          title: Descripcion
        fecha:
          type: string
          title: Fecha
      type: object
      required:
      - id
      - producto_id
      - tipo
      - cantidad
      - descripcion
      - fecha
      title: MovementResponse
    ProductCreate:
      properties:
        codigo:
          type: string
          maxLength: 30
          minLength: 1
          title: Codigo
          description: Codigo unico del producto
        nombre:
          type: string
          maxLength: 120
          minLength: 1
          title: Nombre
          description: Nombre del producto
        precio:
          type: number
          minimum: 0.0
          title: Precio
          description: Precio unitario del producto
        activo:
          type: boolean
          title: Activo
          default: true
      type: object
      required:
      - codigo
      - nombre
      - precio
      title: ProductCreate
    ProductResponse:
      properties:
        id:
          type: integer
          title: Id
        codigo:
          type: string
          title: Codigo
        nombre:
          type: string
          title: Nombre
        precio:
          type: number
          title: Precio
        activo:
          type: boolean
          title: Activo
        stock:
          type: integer
          title: Stock
      type: object
      required:
      - id
      - codigo
      - nombre
      - precio
      - activo
      - stock
      title: ProductResponse
    ProductStatusUpdate:
      properties:
        activo:
          type: boolean
          title: Activo
          description: Estado operativo del producto
      type: object
      required:
      - activo
      title: ProductStatusUpdate
    ProductUpdate:
      properties:
        nombre:
          type: string
          maxLength: 120
          minLength: 1
          title: Nombre
        precio:
          type: number
          minimum: 0.0
          title: Precio
        activo:
          type: boolean
          title: Activo
      type: object
      required:
      - nombre
      - precio
      - activo
      title: ProductUpdate
    ValidationError:
      properties:
        loc:
          items:
            anyOf:
            - type: string
            - type: integer
          type: array
          title: Location
        msg:
          type: string
          title: Message
        type:
          type: string
          title: Error Type
      type: object
      required:
      - loc
      - msg
      - type
      title: ValidationError
